### ISSUE TITLE
Errors upgrading to 1.0

### ISSUE THREAD

**Issue by natew** [mjackson/mach#60]
Not sure why but my old version stopped working after a force restart. I decided to upgrade it and now have a couple issues.

First is when I try and add this:

``` js
var staticPaths = [ '/build/public', '/app/assets', '/web_modules' ];
staticPaths.forEach(function(path) {
  app.use(mach.file, { root: __dirname + path });
});
```

I get these errors on every route, even ones that it shouldn't match:

```
Error: Invalid root directory: undefined
    at file (/Users/nw/Sites/write/node_modules/mach/modules/file.js:77:11)
    at /Users/nw/Sites/write/node_modules/mach/modules/stack.js:115:27
    at compile (/Users/nw/Sites/write/node_modules/mach/modules/stack.js:88:29)
    at stack (/Users/nw/Sites/write/node_modules/mach/modules/stack.js:94:52)
    at Connection.Object.defineProperties.call (/Users/nw/Sites/write/node_modules/mach/modules/Connection.js:207:30)
    at Server.requestHandler (/Users/nw/Sites/write/node_modules/mach/modules/utils/bindApp.js:126:10)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
```

The second problem, when I remove those lines above so it will serve my other routes, is coming from here:

``` js
app.get('*', function() { return template; });
```

And I get:

```
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

**Comment by nicholascloud** [comment]
I am having this exact problem. Vanilla app, no other deps except for mach. I am using 1.0.2.

```javascript
'use strict';
var path = require('path');
var mach = require('mach');

var app = mach.stack();

app.use(mach.file, {
  root: path.join(__dirname, 'public'),
  index: 'index.html'
});

mach.serve(app);
```

Here is the output:

```
Error: Invalid root directory: undefined
    at file (/Users/nicholascloud/projects/temp/test-fblogin/node_modules/mach/modules/middleware/file.js:80:11)
    at Object.defineProperties.use.compiledApp (/Users/nicholascloud/projects/temp/test-fblogin/node_modules/mach/modules/middleware/stack.js:112:27)
    at compile (/Users/nicholascloud/projects/temp/test-fblogin/node_modules/mach/modules/middleware/stack.js:85:29)
    at stack (/Users/nicholascloud/projects/temp/test-fblogin/node_modules/mach/modules/middleware/stack.js:91:52)
    at Connection.Object.defineProperties.call (/Users/nicholascloud/projects/temp/test-fblogin/node_modules/mach/modules/Connection.js:210:30)
    at Server.requestHandler (/Users/nicholascloud/projects/temp/test-fblogin/node_modules/mach/modules/utils/bindApp.js:24:10)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2112:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1970:22)
```

And a debug snapshot of the locals in the mach.file milddleware. You can see that app is null and options is undefined.

![mach.file](https://i.imgur.com/JnwDxqa.png)

**Comment by wavded** [comment]
ran into this today as well, glad a fix landed!
